// <auto-generated />
using System;
using BE_Phygens.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BE_Phygens.Migrations
{
    [DbContext(typeof(PhygensContext))]
    partial class PhygensContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BE_Phygens.Models.AnswerChoice", b =>
                {
                    b.Property<string>("ChoiceId")
                        .HasColumnType("text")
                        .HasColumnName("choiceid");

                    b.Property<string>("ChoiceLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("choicelabel");

                    b.Property<string>("ChoiceText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("choicetext");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("displayorder");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("iscorrect");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("questionid");

                    b.HasKey("ChoiceId");

                    b.HasIndex("QuestionId");

                    b.ToTable("answerchoice", null, t =>
                        {
                            t.HasCheckConstraint("CK_AnswerChoice_DisplayOrder", "displayorder > 0");
                        });
                });

            modelBuilder.Entity("BE_Phygens.Models.Chapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("chapterid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChapterId"));

                    b.Property<string>("ChapterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chaptername");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("displayorder");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.HasKey("ChapterId");

                    b.ToTable("chapter", (string)null);
                });

            modelBuilder.Entity("BE_Phygens.Models.Exam", b =>
                {
                    b.Property<string>("ExamId")
                        .HasColumnType("text")
                        .HasColumnName("examid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("durationminutes");

                    b.Property<int?>("ExamMatrixMatrixId")
                        .HasColumnType("integer");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("examname");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("examtype");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("ispublished");

                    b.HasKey("ExamId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ExamMatrixMatrixId");

                    b.ToTable("exam", null, t =>
                        {
                            t.HasCheckConstraint("CK_Exam_DurationMinutes", "durationminutes > 0");

                            t.HasCheckConstraint("CK_Exam_ExamType", "examtype IN ('15p', '1tiet', 'cuoiky')");
                        });
                });

            modelBuilder.Entity("BE_Phygens.Models.ExamMatrix", b =>
                {
                    b.Property<int>("MatrixId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("matrixid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatrixId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("createdby");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("examname");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("examtype");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<decimal>("TotalPoints")
                        .HasColumnType("numeric")
                        .HasColumnName("totalpoints");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("totalquestions");

                    b.HasKey("MatrixId");

                    b.ToTable("exammatrix", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamMatrix_NumEasy", "numeasy >= 0");

                            t.HasCheckConstraint("CK_ExamMatrix_NumHard", "numhard >= 0");

                            t.HasCheckConstraint("CK_ExamMatrix_NumMedium", "nummedium >= 0");
                        });
                });

            modelBuilder.Entity("BE_Phygens.Models.ExamMatrixDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer")
                        .HasColumnName("chapterid");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("difficultylevel");

                    b.Property<int>("ExamMatrixId")
                        .HasColumnType("integer")
                        .HasColumnName("exammatrixid");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("questioncount");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ExamMatrixId");

                    b.ToTable("ExamMatrixDetail", (string)null);
                });

            modelBuilder.Entity("BE_Phygens.Models.ExamQuestion", b =>
                {
                    b.Property<string>("ExamQuestionId")
                        .HasColumnType("text")
                        .HasColumnName("examquestionid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("addedat");

                    b.Property<string>("ExamId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("examid");

                    b.Property<decimal>("PointsWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("pointsweight");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("questionid");

                    b.Property<int?>("QuestionOrder")
                        .HasColumnType("integer")
                        .HasColumnName("questionorder");

                    b.HasKey("ExamQuestionId");

                    b.HasIndex("ExamId");

                    b.HasIndex("QuestionId");

                    b.ToTable("examquestion", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExamQuestion_PointsWeight", "pointsweight >= 0");

                            t.HasCheckConstraint("CK_ExamQuestion_QuestionOrder", "questionorder > 0");
                        });
                });

            modelBuilder.Entity("BE_Phygens.Models.Explanation", b =>
                {
                    b.Property<string>("ExplanationId")
                        .HasColumnType("text")
                        .HasColumnName("explanationid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("ExplanationText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanationtext");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("questionid");

                    b.HasKey("ExplanationId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("QuestionId");

                    b.ToTable("explanations", (string)null);
                });

            modelBuilder.Entity("BE_Phygens.Models.LearningProgress", b =>
                {
                    b.Property<string>("ProgressId")
                        .HasColumnType("text")
                        .HasColumnName("progressid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<decimal>("AvgScore")
                        .HasColumnType("numeric")
                        .HasColumnName("avgscore");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdated");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topicid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.HasKey("ProgressId");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("learningprogress", null, t =>
                        {
                            t.HasCheckConstraint("CK_LearningProgress_Attempts", "attempts >= 0");

                            t.HasCheckConstraint("CK_LearningProgress_AvgScore", "avgscore >= 0 AND avgscore <= 10");
                        });
                });

            modelBuilder.Entity("BE_Phygens.Models.PhysicsTopic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("text")
                        .HasColumnName("topicid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("displayorder");

                    b.Property<string>("GradeLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gradelevel");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topicname");

                    b.HasKey("TopicId");

                    b.HasIndex("TopicName")
                        .IsUnique();

                    b.ToTable("physicstopic", null, t =>
                        {
                            t.HasCheckConstraint("CK_PhysicsTopic_DisplayOrder", "displayorder > 0");
                        });
                });

            modelBuilder.Entity("BE_Phygens.Models.Question", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasColumnType("text")
                        .HasColumnName("questionid");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficultylevel");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("questiontext");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("questiontype");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topicid");

                    b.HasKey("QuestionId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TopicId");

                    b.ToTable("question", null, t =>
                        {
                            t.HasCheckConstraint("CK_Question_DifficultyLevel", "difficultylevel IN ('easy', 'medium', 'hard')");

                            t.HasCheckConstraint("CK_Question_QuestionType", "questiontype IN ('multiple_choice', 'true_false', 'essay')");
                        });
                });

            modelBuilder.Entity("BE_Phygens.Models.StudentAnswer", b =>
                {
                    b.Property<string>("AnswerId")
                        .HasColumnType("text")
                        .HasColumnName("answerid");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answeredat");

                    b.Property<string>("AttemptId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attemptid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("iscorrect");

                    b.Property<decimal>("PointsEarned")
                        .HasColumnType("numeric")
                        .HasColumnName("pointsearned");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("questionid");

                    b.Property<string>("SelectedChoiceId")
                        .HasColumnType("text")
                        .HasColumnName("selectedchoiceid");

                    b.Property<string>("StudentTextAnswer")
                        .HasColumnType("text")
                        .HasColumnName("studenttextanswer");

                    b.HasKey("AnswerId");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedChoiceId");

                    b.ToTable("studentanswer", null, t =>
                        {
                            t.HasCheckConstraint("CK_StudentAnswer_PointsEarned", "pointsearned >= 0");
                        });
                });

            modelBuilder.Entity("BE_Phygens.Models.StudentAttempt", b =>
                {
                    b.Property<string>("AttemptId")
                        .HasColumnType("text")
                        .HasColumnName("attemptid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("endtime");

                    b.Property<string>("ExamId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("examid");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("numeric")
                        .HasColumnName("maxscore");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starttime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("numeric")
                        .HasColumnName("totalscore");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.HasKey("AttemptId");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("studentattempt", null, t =>
                        {
                            t.HasCheckConstraint("CK_StudentAttempt_MaxScore", "maxscore > 0 AND maxscore <= 10");

                            t.HasCheckConstraint("CK_StudentAttempt_Status", "status IN ('in_progress', 'completed', 'abandoned')");

                            t.HasCheckConstraint("CK_StudentAttempt_TotalScore", "totalscore >= 0 AND totalscore <= 10");
                        });
                });

            modelBuilder.Entity("BE_Phygens.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_Role", "role IN ( 'student', 'admin')");
                        });
                });

            modelBuilder.Entity("BE_Phygens.Models.AnswerChoice", b =>
                {
                    b.HasOne("BE_Phygens.Models.Question", "Question")
                        .WithMany("AnswerChoices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BE_Phygens.Models.Exam", b =>
                {
                    b.HasOne("BE_Phygens.Models.User", "Creator")
                        .WithMany("CreatedExams")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BE_Phygens.Models.ExamMatrix", null)
                        .WithMany("Exams")
                        .HasForeignKey("ExamMatrixMatrixId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BE_Phygens.Models.ExamMatrixDetail", b =>
                {
                    b.HasOne("BE_Phygens.Models.Chapter", "Chapter")
                        .WithMany("ExamMatrixDetails")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_Phygens.Models.ExamMatrix", "ExamMatrix")
                        .WithMany("ExamMatrixDetails")
                        .HasForeignKey("ExamMatrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("ExamMatrix");
                });

            modelBuilder.Entity("BE_Phygens.Models.ExamQuestion", b =>
                {
                    b.HasOne("BE_Phygens.Models.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_Phygens.Models.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BE_Phygens.Models.Explanation", b =>
                {
                    b.HasOne("BE_Phygens.Models.User", "Creator")
                        .WithMany("CreatedExplanations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BE_Phygens.Models.Question", "Question")
                        .WithMany("Explanations")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BE_Phygens.Models.LearningProgress", b =>
                {
                    b.HasOne("BE_Phygens.Models.PhysicsTopic", "Topic")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_Phygens.Models.User", "User")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_Phygens.Models.Question", b =>
                {
                    b.HasOne("BE_Phygens.Models.Chapter", null)
                        .WithMany("Questions")
                        .HasForeignKey("ChapterId");

                    b.HasOne("BE_Phygens.Models.User", "Creator")
                        .WithMany("CreatedQuestions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BE_Phygens.Models.PhysicsTopic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("BE_Phygens.Models.StudentAnswer", b =>
                {
                    b.HasOne("BE_Phygens.Models.StudentAttempt", "Attempt")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_Phygens.Models.Question", "Question")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_Phygens.Models.AnswerChoice", "SelectedChoice")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("SelectedChoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Attempt");

                    b.Navigation("Question");

                    b.Navigation("SelectedChoice");
                });

            modelBuilder.Entity("BE_Phygens.Models.StudentAttempt", b =>
                {
                    b.HasOne("BE_Phygens.Models.Exam", "Exam")
                        .WithMany("StudentAttempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_Phygens.Models.User", "User")
                        .WithMany("StudentAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE_Phygens.Models.AnswerChoice", b =>
                {
                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("BE_Phygens.Models.Chapter", b =>
                {
                    b.Navigation("ExamMatrixDetails");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BE_Phygens.Models.Exam", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("StudentAttempts");
                });

            modelBuilder.Entity("BE_Phygens.Models.ExamMatrix", b =>
                {
                    b.Navigation("ExamMatrixDetails");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("BE_Phygens.Models.PhysicsTopic", b =>
                {
                    b.Navigation("LearningProgresses");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BE_Phygens.Models.Question", b =>
                {
                    b.Navigation("AnswerChoices");

                    b.Navigation("ExamQuestions");

                    b.Navigation("Explanations");

                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("BE_Phygens.Models.StudentAttempt", b =>
                {
                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("BE_Phygens.Models.User", b =>
                {
                    b.Navigation("CreatedExams");

                    b.Navigation("CreatedExplanations");

                    b.Navigation("CreatedQuestions");

                    b.Navigation("LearningProgresses");

                    b.Navigation("StudentAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
